# Generated by Django 4.1.7 on 2023-03-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_newspaper_options_alter_redactor_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="redactor",
            options={
                "ordering": ["username"],
                "verbose_name": "Publisher",
                "verbose_name_plural": "Publishers",
            },
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
