# Generated by Django 4.1.7 on 2023-04-01 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_redactor_options_alter_topic_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspaper",
            options={"ordering": ["-published_date"]},
        ),
        migrations.AlterModelOptions(
            name="redactor",
            options={
                "ordering": ["username"],
                "verbose_name": "Redactor",
                "verbose_name_plural": "Redactors",
            },
        ),
        migrations.RenameField(
            model_name="newspaper",
            old_name="publishers",
            new_name="redactors",
        ),
        migrations.AlterField(
            model_name="newspaper",
            name="published_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="newspaper",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="newspaper",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.topic"
            ),
        ),
    ]
